GET http://192.168.100.3:8080/api/profits/sessions


###
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "bear"
}

###
GET http://192.168.100.3:8080/api/categories/1


###
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "kane",
  "price": 250.0,
  "stockQuantity": 20,
  "category": {
    "id": 2,
    "name": "sprit"

  }
}

###
### GET request to example server
GET http://localhost:8080/api/categories

